name: check endline data

on:
  # schedule:
  #   - cron: "0 17 * * *"  
  workflow_dispatch:
    branches:
      - '*'

jobs:
  check-endline-data:
    runs-on: ubuntu-latest
    container: rocker/geospatial:4.1.2
    env:
      GIT_CRYPT_KEY64: ${{ secrets.GIT_CRYPT_KEY64 }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
          git-crypt libxt6 libglpk-dev
          
      - name: Decrypt repository using symmetric key
        run: |
          echo $GIT_CRYPT_KEY64 > git_crypt_key.key64 && base64 -di git_crypt_key.key64 > git_crypt_key.key && git-crypt unlock git_crypt_key.key
          rm git_crypt_key.key git_crypt_key.key64
          
      - name: Install packages from renv.lock (with cache)
        if: ${{ !env.ACT }}  
        uses: r-lib/actions/setup-renv@master
        with:
          cache-version: 2

      - name: Install packages from renv.lock (local, no cache)
        if: ${{ env.ACT }}  
        run: |
          renv::restore()
        shell: Rscript {0}
        
      - name: Run daily progress and data check workflow
        run: |
          targets::tar_make(survey_progress_deployed)
          targets::tar_make(data_quality_deployed)
        shell: Rscript {0}
        
      - name: Deploy and archive reports
        run: |
          targets::tar_make(survey_progress_archive_deployed)
          targets::tar_make(data_quality_archive_deployed)
        shell: Rscript {0}
          
      - name: Email report
        run: |
          targets::tar_make(daily_report_emailed)
        shell: Rscript {0}
          
      - name: Commit and push files
        run: |
          git config --global user.email "ernest@guevarra.io"
          git config --global user.name "ernestguevarra"
          git add .
          git diff-index --quiet HEAD || git commit -m "deploy daily report"
          git push
      